from .config_editor import ConfigEditor
from .communication_dialog import CommunicationDialog
from .asset_manager import AssetManagerDialog
from .import_plugin import ImportPluginDialog
from .version_manager import VersionManagerDialog
from .template_market import TemplateMarketDialog
from .sdk_docs_viewer import SdkDocsViewerDialog
from .settings import SettingsDialog
from .crash_viewer import CrashViewerDialog
